config:
  service:
    name: jackson-ui
    namespace: default
    port: 8080
    labelName: jackson
  fullnameOverride: spring-boot-ui
  appName: spring-boot-ui
  image:
    repository: yradsmikwalmartacr.azurecr.io/project-jackson-ui
    tag: "1.0"
  enableVirtualService: true
  enableDestinationRule: true
# subcomponents:
#   canary:
#     config:
#       service:
#         port: 8080
#         labelName: jackson
#   stable:
#     config:
#       service:
#         port: 8080
#         labelName: jackson
