apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.labelName }}
spec:
  selector:
    app: {{ .Values.appName }} # Deployment name tag
  ports:
  - name: http
    port: {{ .Values.service.port }}

{{- if .Values.enableDestinationRule }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.labelName }}
spec:
  host: "{{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local"
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
{{- end }}

{{- if .Values.enableVirtualService }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
    # https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService
  gateways: # The default `mesh` value for when left blank is doesn't seem to propigate the rule properly. For now, always use a list of FQDN gateways
    - istio-autogenerated-k8s-ingress.istio-system.svc.cluster.local # must be FQDN if VirtualService in different NS than Gateway
  hosts:
    # Services in Kubernetes expose their endpoint using a common DNS pattern.
    # It looks like: <Service Name>.<Namespace Name>.svc.cluster.local
    # if not a FQDN then Istio assumes the namespace of the THIS VirtualService
    # - "{{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local"
    - "*"
  http:
  - route:
    - destination:
        host: "{{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local"
        subset: stable
        port: 
          number: {{ .Values.service.port }}
      weight: {{ if .Values.service.canaryWeight }} {{ .Values.service.stableWeight}} {{ else }} 100 {{ end }}
    - destination:
        host: "{{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local"
        subset: canary
        port: 
          number: {{ .Values.service.port }}
      weight: {{ if .Values.service.canaryWeight }} {{ .Values.service.canaryWeight}} {{ else }} 0 {{ end }}
    {{ if .Values.service.match }} # WARNING: THIS IS REALLY MESSY. FIX!
    match:
    {{if .Values.service.match.uri }}
    - uri:
      {{ if .Values.service.match.uri.prefix }}
        prefix: {{ .Values.service.match.uri.prefix }} 
      {{end}}
    {{end}}
    {{end}}
{{- end }}
